### ISSUE TITLE
state node: discarded duplicate state payload

### ISSUE THREAD

**Issue by Langer75** [coldfire84/node-red-alexa-home-skill-v3-web#99] opened 2020-01-27 22:40 UTC
I'm not sure if it is a bug but i got the following output continously in my node-red console:
27 Jan 23:33:22 - [info] [alexa-smart-home-v3-state:Bad EG] Bad EG state node: discarded duplicate state payload
27 Jan 23:33:23 - [info] [alexa-smart-home-v3-state:WC OG] WC OG state node: discarded duplicate state payload
27 Jan 23:33:23 - [info] [alexa-smart-home-v3-state:Bad OG] Bad OG state node: discarded duplicate state payload
27 Jan 23:33:24 - [info] [alexa-smart-home-v3-state:Philipps Licht] Philipps Licht state node: discarded duplicate state payload
27 Jan 23:33:30 - [info] [alexa-smart-home-v3-state:Küchenlicht] Küchenlicht state node: discarded duplicate state payload
27 Jan 23:33:30 - [info] [alexa-smart-home-v3-state:Arbeitsplatte] Arbeitsplatte state node: discarded duplicate state payload
27 Jan 23:33:31 - [info] [alexa-smart-home-v3-state:Kücheneingang] Kücheneingang state node: discarded duplicate state payload
27 Jan 23:33:32 - [info] [alexa-smart-home-v3-state:Schlafecke] Schlafecke state node: discarded duplicate state payload
27 Jan 23:33:32 - [info] [alexa-smart-home-v3-state:Treppe DG] Treppe DG state node: discarded duplicate state payload
27 Jan 23:33:33 - [info] [alexa-smart-home-v3-state:Ankleide] Ankleide state node: discarded duplicate state payload
27 Jan 23:33:33 - [info] [alexa-smart-home-v3-state:Durchgang] Durchgang state node: discarded duplicate state payload
27 Jan 23:33:34 - [info] [alexa-smart-home-v3-state:Arbeitszimmer] Arbeitszimmer state node: discarded duplicate state payload
27 Jan 23:33:35 - [info] [alexa-smart-home-v3-state:Wohnzimmerlampe] Wohnzimmerlampe state node: discarded duplicate state payload
27 Jan 23:33:36 - [info] [alexa-smart-home-v3-state:Esstischeins] Esstischeins state node: discarded duplicate state payload
27 Jan 23:33:36 - [info] [alexa-smart-home-v3-state:Esstischbeide] Esstischbeide state node: discarded duplicate state payload
27 Jan 23:33:36 - [info] [alexa-smart-home-v3-state:Esstischzwei] Esstischzwei state node: discarded duplicate state payload
27 Jan 23:33:41 - [info] [alexa-smart-home-v3-state:Spitzgaube] Spitzgaube state node: discarded duplicate state payload
27 Jan 23:33:41 - [info] [alexa-smart-home-v3-state:Wohn OG] Wohn OG state node: discarded duplicate state payload
27 Jan 23:33:44 - [info] [alexa-smart-home-v3-state:Millas Licht] Millas Licht state node: discarded duplicate state payload
27 Jan 23:33:44 - [info] [alexa-smart-home-v3-state:Treppe OG] Treppe OG state node: discarded duplicate state payload
27 Jan 23:33:45 - [info] [alexa-smart-home-v3-state:Eingangsbereich] Eingangsbereich state node: discarded duplicate state payload
27 Jan 23:33:45 - [info] [alexa-smart-home-v3-state:Eingangstreppe] Eingangstreppe state node: discarded duplicate state payload
27 Jan 23:33:45 - [info] [alexa-smart-home-v3-state:Flurlicht] Flurlicht state node: discarded duplicate state payload
27 Jan 23:33:49 - [info] [alexa-smart-home-v3-state:Schlaf Bernhard] Schlaf Bernhard state node: discarded duplicate state payload
27 Jan 23:33:49 - [info] [alexa-smart-home-v3-state:Lichterkette] Lichterkette state node: discarded duplicate state payload
27 Jan 23:33:51 - [info] [alexa-smart-home-v3-state:Wohn Bernhard] Wohn Bernhard state node: discarded duplicate state payload
27 Jan 23:33:52 - [info] [alexa-smart-home-v3-state:Bad EG] Bad EG state node: discarded duplicate state payload
27 Jan 23:33:53 - [info] [alexa-smart-home-v3-state:WC OG] WC OG state node: discarded duplicate state payload
27 Jan 23:33:53 - [info] [alexa-smart-home-v3-state:Bad OG] Bad OG state node: discarded duplicate state payload
27 Jan 23:33:54 - [info] [alexa-smart-home-v3-state:Philipps Licht] Philipps Licht state node: discarded duplicate state payload
27 Jan 23:34:00 - [info] [alexa-smart-home-v3-state:Küchenlicht] Küchenlicht state node: discarded duplicate state payload
27 Jan 23:34:00 - [info] [alexa-smart-home-v3-state:Arbeitsplatte] Arbeitsplatte state node: discarded duplicate state payload
27 Jan 23:34:01 - [info] [alexa-smart-home-v3-state:Kücheneingang] Kücheneingang state node: discarded duplicate state payload

What does it mean?

**Comment by coldfire84** [comment] 2020-01-27 23:12
The nodes are operating "by design" in that you are sending a duplicate state message (exactly same state as last update) and the nodes are filtering/ dropping this at the edge in order to ensure the service scales to thousands of users. A like-for-like update is of no value, but consumes server-side resources at scale.

**Comment by coldfire84** [comment] 2020-01-27 23:13
The debug messages are there to help people troubleshoot sending state updates, but I may look to eliminate the "log spam" in a later release.

**Comment by coldfire84** [comment] 2020-04-23 08:43
This issue is resolved in node-red-contrib-alexa-smart-home release 0.4.67 onwards.

**Closed as completed by coldfire84** 2020-04-23 08:43 UTC
