### ISSUE TITLE
Web Server (red.cb-net.co.uk) is down.

### ISSUE THREAD

**Issue by richard-scott** [coldfire84/node-red-alexa-home-skill-v3-web#170] opened 2023-03-07 20:59 UTC
<img width="1000" alt="Screenshot 2023-03-07 at 20 53 33" src="https://user-images.githubusercontent.com/5149834/223550388-58e632c1-b96c-4ec8-a13d-a6c384b45b80.png">

**Comment by FrankGiesecke** [comment] 2023-03-07 21:28
I think this one relates to https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/issues/168

**Comment by coldfire84** [comment] 2023-03-07 22:22
Yes, effectively a duplicate of #168

**Closed as completed by coldfire84** 2023-03-07 22:22 UTC
