### ISSUE TITLE
Google Home: State not updated in app when locally changed

### ISSUE THREAD

**Issue by davidmuc** [coldfire84/node-red-alexa-home-skill-v3-web#113] opened 2020-05-02 00:07 UTC
Sending a command from my Google Home via alexa-home-skill to my homematic home automation system works great. Im using the ccu-alexa node (https://flows.nodered.org/node/node-red-contrib-ccu) to pass commands on to my homematic ccu (control unit).
When I locally change a device state (e.g. by switching it off with the device's hardware switch), the state is being updated in the ccu-alexa-node, as you can see in the debug info, but the new state is not being reflected in my Google Home app: in the app, the light is still shown as ON.

So it seems communications only works one-way from Google Assistant via alexa-home-skill to homematic, but not the other way round. Am I doing somehting wrong?!

<img width="1154" alt="Bildschirmfoto 2020-05-02 um 02 06 21" src="https://user-images.githubusercontent.com/5596124/80849900-887a2a00-8c19-11ea-9c19-4afe078d65bd.png">

**Comment by coldfire84** [comment] 2020-05-02 08:51
Can you confirm your username? If you can message (via [Slack](https://join.slack.com/t/cb-net/shared_invite/enQtODc1ODgzNzkxNTM3LTYwZGZmNjAxZWZmYTU4ZDllOGM3OTMxMzI4NzRlZmUzZmQ4NDljZWZiOTIwNTYzYjJmZjVlYzhhYWFiNThlMDA)) me console logs from Node-RED I'll then trace against the service to see if the state updates are actually being sent to Google.

**Comment by coldfire84** [comment] 2020-05-02 09:18
Having checked the skill it *is* sending updates (for lots of users). I also checked in the Google Home app and can replicate the behavior you flag:
- Open device in Google Home, app shows device OFF
- Use Alexa/ a physical button to turn device ON
- Google Home still shows device still OFF (correct state update *is* sent via the skill though)
- In Google Home, go back to "all devices" view and then back into the device itself it shows power state as ON

Reviewing the material on [Report State](https://developers.google.com/assistant/smarthome/develop/report-state) I'm not sure the updates are supposed to 'appear' on the app when a single device is already opened. It looks as if Report State was designed to reduce visual feedback delay when making changes in the Google Home app itself, a delay that would be caused by a command (via EXECUTE) and then QUERY to check state has changed. 

Video in the link doesn't show the display updating in real-time when the **thermostat** is changed.

**Comment by hisham211** [comment] 2020-08-04 02:19
I'm having the same issue, but with Alexa. 

Setup:
Home Assistant .112.4
Node-Red 7.0.0

I can issue commands from Alexa and have lights turn on. However, if I trigger the device manually or through Home Assistant, the device state doesn't update in Alexa app on iOS.

I tried using an entity state node to feed back the state to an Alexa Smart Home v3 State Node through the following function, but no luck:
if (msg.state == "On" ) {
    msg.acknowledge = [true]
    msg.payload = {state: {"power" : "ON"}
    }
return msg;
}

if (msg.state == "Off" ) {
    msg.acknowledge = [true]
    msg.payload = {state: {"power" : "OFF"}
    }
return msg;
}

**Comment by djaahn** [comment] 2020-12-09 20:14
Hi

I'm having the same problem. My setup is similar to Davidmuc's regarding use of nodes as descriped in Node-RED. 

As opposed to the others I'm getting a circular reference warning from my Payload?

Any advise/sollution?

Regards 
Mads

Great integration otherwise!

**Comment by davidmuc** [comment] 2020-12-09 20:23
I'm using **NORA** by now and managed to get things up and running smoothly. See [node-red-contrib-nora](https://flows.nodered.org/node/node-red-contrib-nora)
(...and consider it solved ;-)

**Comment by coldfire84** [comment] 2020-12-09 21:54
@davidmuc sorry to hear you moved services, but good to hear you fixed your issue. 

I just want to be sure I understand correctly - NORA "out of band state updates" trigger an update in the Google Home app? I ask because I continue to monitor whether the situation with this has changed, and other developers continue to report similar experiences to what I outlined above, for example: https://stackoverflow.com/questions/61644784/google-home-report-state-request-is-working-but-not-showing-expected-result and https://stackoverflow.com/questions/61271129/google-smart-home-app-doesnt-update-the-state-of-the-device-in-the-real-time-af.

**Comment by coldfire84** [comment] 2020-12-09 21:56
@djaahn can you share you payload/ share more info in the Slack Workspace mentioned in the docs.

**Comment by coldfire84** [comment] 2021-01-15 22:45
Closing as this is, sadly, by design. Will continue to monitor, and when/ if possible add functionality to the service.

**Closed as completed by coldfire84** 2021-01-15 22:45 UTC
